version: '3.2'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_DATABASE=hotel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=abc
    container_name: mysql
    volumes:
      - ./mysql-volume:/var/lib/mysql:rw
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src